name: Checks after any release is published
on:
  release:
    types: [ 'published' ]

jobs:
  validate-github-action:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          curl -X POST https://api.github.com/repos/joaopapereira/releaser/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "tool_released", "client_payload": { "tagName": "${{ github.event.release.tag_name }}", "repo": "${{ github.repository }}", "toolName": "imgpkg" }}'
