name: running-test

"on":
  workflow_dispatch:
jobs:
  check-contains:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issues Summary
        run: |
          echo "SUMMARY='Something'" >> $GITHUB_ENV
      - name: Success with contains
        if: success() && ${{ env.SUMMARY }} == 'Something'
        run: |
          echo ${{ env.SUMMARY == 'Something' }}
          echo "with contains"
          echo "${{ env.SUMMARY }}"
      - name: Success without contains
        if: success() && ${{ env.SUMMARY }} != 'Something'
        run: |
          echo ${{ env.SUMMARY != 'Something' }}
          echo "without contains"
          echo "${{ env.SUMMARY }}"
      - name: On fail
        if: failure()
        run: |
          echo ${{ env.SUMMARY != 'Something' }}
          echo "without contains"
          echo "${{ env.SUMMARY }}"
