name: running-test

"on":
  workflow_dispatch:
jobs:
  check-contains:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issues Summary
        id: stuff
        run: |
          exit 1
          echo "SUMMARY='Something'" >> $GITHUB_ENV
          echo '::set-output name=summary::something plus something else'
          echo '::set-output name=action_echo::disabled'
      - name: Success with contains
        if: steps.stuff.outputs.summary == ''
        run: |
          echo ${{ env.SUMMARY == 'Something' }}
          echo "with contains"
          echo "Summary was: ${{ steps.stuff.outputs.summary }} <-"
          echo "action echo: ${{ steps.stuff.outputs.action_echo }} <-"
          echo "${{ env.SUMMARY }}"
      - name: Success without contains
        if: steps.stuff.outputs.summary == 'something plus something else'
        run: |
          echo ${{ env.SUMMARY != 'Something' }}
          echo "without contains"
          echo "${{ env.SUMMARY }}"
      - name: On fail
        if: failure()
        run: |
          echo ${{ env.SUMMARY != 'Something' }}
          echo "without contains"
          echo "${{ env.SUMMARY }}"
