name: test

"on":
  push:
    branches:
      - main



jobs:
  test-job:
        uses: vmware-tanzu/carvel-release-scripts/.github/workflows/trivy-scan.yml@main
        with:
          repo: vmware-tanzu/carvel-imgpkg
          tool: imgpkg
          goVersion: 1.17.0
          slackWebhookURL: ${{ secrets.SLACK_WEBHOOK_URL }}
